### ISSUE TITLE
Issues with conditionals.ts

### ISSUE THREAD

**Issue by tonisives** [jherr/no-bs-ts#5]
I have installed node-fetch dependency. However, the conditionals.ts has an error

```
Argument of type 'unknown' is not assignable to parameter of type 'PokemonResults'.ts(2345)
```

<img width="1163" alt="Screenshot 2022-01-19 at 17 13 04" src="https://user-images.githubusercontent.com/1083534/150110141-a2150ed7-84a8-4da6-b7d7-cf7a12915209.png">

The data.json response from the fetch function returns `Promise<unknown>` type

Fix is to cast data to `Promise<PokemonResults>

```
fetch(url)
      .then((data) => data.json() as Promise<PokemonResults>)
      .then((data) => cb(data));
```

There is also error with fetch.

```
ts conditionals.ts
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/tonis/workspace/web/ti-no-bs-ts/ts-basics/node_modules/node-fetch/src/index.js from /Users/tonis/workspace/web/ti-no-bs-ts/ts-basics/conditionals.ts not supported.
Instead change the require of index.js in /Users/tonis/workspace/web/ti-no-bs-ts/ts-basics/conditionals.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/tonis/workspace/web/ti-no-bs-ts/ts-basics/conditionals.ts:15:38)
    at Module.m._compile (/Users/tonis/workspace/web/ti-no-bs-ts/ts-basics/node_modules/ts-node/dist/index.js:735:29)
    at Object.require.extensions.<computed> [as .ts] (/Users/tonis/workspace/web/ti-no-bs-ts/ts-basics/node_modules/ts-node/dist/index.js:737:16)
    at main (/Users/tonis/workspace/web/ti-no-bs-ts/ts-basics/node_modules/ts-node/dist/bin.js:238:16)
    at Object.<anonymous> (/Users/tonis/workspace/web/ti-no-bs-ts/ts-basics/node_modules/ts-node/dist/bin.js:351:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

The solution is to downgrade fetch to v2. [link](https://stackoverflow.com/a/69087361/599743). `yarn add node-fetch` adds v3 automatically

**Comment by Lam-Big-Water** [comment]
Thank you so much!
